[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ffmpeg==1.4",
    "flask-socketio==5.4.1",
    "flask>=3.1.0",
    "yt-dlp>=2025.4.30",
]
